# Generated by Django 5.0.3 on 2024-10-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='material',
            fields=[
                ('material_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('material_name', models.CharField(default='none', max_length=32, unique=True)),
                ('material_unit', models.CharField(choices=[('KG', 'Kilograms'), ('PCS', 'Piece')], default='KG', max_length=16)),
                ('material_weight', models.IntegerField(default=0)),
            ],
        ),
    ]
