# Generated by Django 5.0.3 on 2024-10-22 19:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agv_data',
            fields=[
                ('data_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('car_id', models.IntegerField()),
                ('agv_state', models.IntegerField()),
                ('agv_speed', models.FloatField()),
                ('agv_battery', models.FloatField()),
                ('previous_waypoint', models.IntegerField()),
                ('distance', models.FloatField()),
                ('next_waypoint', models.IntegerField()),
                ('time_stamp', models.DateTimeField(blank=True)),
                ('distance_sum', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='agv_identify',
            fields=[
                ('agv_id', models.IntegerField(primary_key=True, serialize=False)),
                ('max_speed', models.IntegerField(default=0)),
                ('battery_capacity', models.IntegerField(default=0)),
                ('max_load', models.IntegerField(default=0)),
                ('guidance_type', models.CharField(blank=True, choices=[('line_following', 'line_following'), ('image_processing', 'image_processing')], max_length=255)),
                ('is_busy', models.BooleanField(default=True)),
                ('is_connected', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='agv_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_id', models.IntegerField(default=0)),
                ('state_name', models.CharField(default='None', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='agv_error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_id', models.IntegerField(default=0, unique=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('error_msg', models.CharField(default='', max_length=16)),
                ('previous_waypoint', models.IntegerField()),
                ('next_waypoint', models.IntegerField()),
                ('order_number', models.IntegerField()),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agv_management.agv_identify')),
            ],
        ),
    ]
