# Generated by Django 5.0.3 on 2024-10-23 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agv_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prevNode', models.IntegerField(default=0)),
                ('nextNode', models.IntegerField(default=0)),
                ('distance', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='agv_data',
            name='distance',
        ),
        migrations.AddField(
            model_name='agv_data',
            name='current_position',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agv_management.position'),
        ),
    ]
