# Generated by Django 5.0.3 on 2024-10-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agv_management', '0003_remove_agv_data_current_position_agv_data_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agv_error',
            name='car_id',
            field=models.IntegerField(),
        ),
    ]
