# Generated by Django 5.0.3 on 2024-11-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agv_management', '0004_alter_agv_error_car_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agv_identify',
            old_name='is_busy',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='agv_identify',
            name='parking_lot',
            field=models.IntegerField(default=0),
        ),
    ]
