# Generated by Django 5.0.3 on 2024-09-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order_data',
            fields=[
                ('request_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('order_number', models.IntegerField(default=0)),
                ('load_name', models.CharField(default='none', max_length=16)),
                ('load_amount', models.PositiveIntegerField(default=0)),
                ('load_weight', models.IntegerField(default=0)),
                ('start_time', models.CharField(default='00:00:00', max_length=16)),
                ('begin_waypoint', models.PositiveBigIntegerField(default=0)),
                ('end_waypoint', models.PositiveBigIntegerField(default=0)),
                ('schedule_status', models.BooleanField(default=False)),
                ('process_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='schedule_data',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_number', models.IntegerField(default=0)),
                ('order_date', models.DateField()),
                ('load_name', models.CharField(default='none', max_length=16)),
                ('load_weight', models.FloatField(default=0)),
                ('agv_id', models.IntegerField(default=0)),
                ('battery_loss', models.IntegerField()),
                ('total_trip', models.FloatField()),
                ('start_time', models.CharField(default='00:00:00', max_length=16)),
                ('end_time', models.CharField(default='00:00:00', max_length=16)),
                ('begin_waypoint', models.IntegerField(default=0)),
                ('end_waypoint', models.IntegerField(default=0)),
                ('process_status', models.BooleanField(default=False)),
            ],
        ),
    ]
