# Generated by Django 5.0.3 on 2024-10-22 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='order_data',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('load_amount', models.PositiveIntegerField(default=0)),
                ('load_weight', models.IntegerField(default=0)),
                ('start_time', models.CharField(default='00:00:00', max_length=16)),
                ('start_point', models.PositiveBigIntegerField(default=0)),
                ('end_point', models.PositiveBigIntegerField(default=0)),
                ('is_processed', models.BooleanField(default=False)),
                ('load_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='material_management.material', to_field='material_name')),
                ('user_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='schedule_data',
            fields=[
                ('schedule_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('load_name', models.CharField(default='none', max_length=16)),
                ('load_weight', models.FloatField(default=0)),
                ('load_amount', models.PositiveIntegerField(default=0)),
                ('agv_id', models.IntegerField(default=0)),
                ('est_energy', models.IntegerField()),
                ('est_distance', models.FloatField()),
                ('est_start_time', models.CharField(default='00:00:00', max_length=16)),
                ('est_end_time', models.CharField(default='00:00:00', max_length=16)),
                ('start_point', models.IntegerField(default=0)),
                ('end_point', models.IntegerField(default=0)),
                ('is_processed', models.BooleanField(default=False)),
                ('instruction_set', models.CharField(default='', max_length=1024)),
                ('order_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests_management.order_data')),
            ],
        ),
    ]
