# Generated by Django 5.0.3 on 2024-11-14 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_data',
            name='is_processed',
        ),
    ]
