# Generated by Django 5.0.3 on 2024-11-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_management', '0003_alter_order_data_load_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule_data',
            name='order_number',
            field=models.IntegerField(default=0),
        ),
    ]
