# Generated by Django 5.0.3 on 2024-11-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_management', '0004_alter_schedule_data_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_data',
            old_name='order_id',
            new_name='request_id',
        ),
        migrations.AddField(
            model_name='order_data',
            name='order_number',
            field=models.IntegerField(default=0),
        ),
    ]
