# Generated by Django 5.0.3 on 2024-11-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_management', '0005_rename_order_id_order_data_request_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule_data',
            name='instruction_set',
            field=models.JSONField(),
        ),
    ]
