# Generated by Django 5.0.3 on 2024-11-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_management', '0006_alter_schedule_data_instruction_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_data',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
