# Generated by Django 4.2 on 2025-04-05 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_management', '0007_order_data_is_scheduled'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule_data',
            name='session_id',
            field=models.CharField(default='00000000000000', max_length=14),
        ),
    ]
